services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama_agent
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./docs:/app/docs
      - ./memory:/app/memory
      - ./learnings:/app/learnings
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
    tty: true
    stdin_open: true
