services:
  agent:
    build: .
    container_name: ollama_agent
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./docs:/app/docs
      - ./memory:/app/memory
      - ./learnings:/app/learnings
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
    tty: true
    stdin_open: true
